# Configuration file for MegaLinter
# See all available variables at: https://megalinter.io/latest/configuration/ and in linters documentation
# See .NET Flavor at: https://megalinter.io/latest/flavors/dotnet/
APPLY_FIXES: all
ENABLE:
  - REPOSITORY
  - COPYPASTE
  - SPELL
  - ACTION
  - CSHARP
  - MARKDOWN
  - POWERSHELL
  - SQL
  - HTML
  - CSS
  - JSON
  - XML
  - YAML
DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
PRINT_ALPACA: true
SHOW_ELAPSED_TIME: true
